"""empty message

Revision ID: 000000000100
Revises: 000000000000
Create Date: 2023-02-16 12:39:38.278965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '000000000100'
down_revision = '000000000000'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_state',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('block_height', sa.BigInteger(), nullable=False),
    sa.Column('app_hash', sa.LargeBinary(), nullable=False),
    sa.PrimaryKeyConstraint('created_at')
    )
    op.create_table('cert_entities',
    sa.Column('sn', sa.LargeBinary(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('public_key', sa.LargeBinary(), nullable=False),
    sa.Column('pem_serialized', sa.Text(), nullable=False),
    sa.Column('not_valid_after', sa.DateTime(), nullable=False),
    sa.Column('not_valid_before', sa.DateTime(), nullable=False),
    sa.Column('revocated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('sn')
    )
    op.create_index(op.f('ix_cert_entities_name'), 'cert_entities', ['name'], unique=False)
    op.create_index(op.f('ix_cert_entities_public_key'), 'cert_entities', ['public_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cert_entities_public_key'), table_name='cert_entities')
    op.drop_index(op.f('ix_cert_entities_name'), table_name='cert_entities')
    op.drop_table('cert_entities')
    op.drop_table('app_state')
    # ### end Alembic commands ###
